/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendreRouteImport } from './routes/vendre'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CalculRouteImport } from './routes/calcul'
import { Route as AlertesRouteImport } from './routes/alertes'
import { Route as AgenceRouteImport } from './routes/agence'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BiensIndexRouteImport } from './routes/biens/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as BiensSlugRouteImport } from './routes/biens/$slug'
import { Route as AdminParametresRouteImport } from './routes/admin/parametres'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminEquipeRouteImport } from './routes/admin/equipe'
import { Route as AdminContactsRouteImport } from './routes/admin/contacts'
import { Route as AdminBiensIndexRouteImport } from './routes/admin/biens/index'
import { Route as AdminBiensNouveauRouteImport } from './routes/admin/biens/nouveau'
import { Route as AdminBiensIdRouteImport } from './routes/admin/biens/$id'

const VendreRoute = VendreRouteImport.update({
  id: '/vendre',
  path: '/vendre',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculRoute = CalculRouteImport.update({
  id: '/calcul',
  path: '/calcul',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertesRoute = AlertesRouteImport.update({
  id: '/alertes',
  path: '/alertes',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenceRoute = AgenceRouteImport.update({
  id: '/agence',
  path: '/agence',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BiensIndexRoute = BiensIndexRouteImport.update({
  id: '/biens/',
  path: '/biens/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const BiensSlugRoute = BiensSlugRouteImport.update({
  id: '/biens/$slug',
  path: '/biens/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminParametresRoute = AdminParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEquipeRoute = AdminEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactsRoute = AdminContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBiensIndexRoute = AdminBiensIndexRouteImport.update({
  id: '/biens/',
  path: '/biens/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBiensNouveauRoute = AdminBiensNouveauRouteImport.update({
  id: '/biens/nouveau',
  path: '/biens/nouveau',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBiensIdRoute = AdminBiensIdRouteImport.update({
  id: '/biens/$id',
  path: '/biens/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agence': typeof AgenceRoute
  '/alertes': typeof AlertesRoute
  '/calcul': typeof CalculRoute
  '/contact': typeof ContactRoute
  '/vendre': typeof VendreRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/equipe': typeof AdminEquipeRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/biens/$slug': typeof BiensSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/biens/': typeof BiensIndexRoute
  '/admin/biens/$id': typeof AdminBiensIdRoute
  '/admin/biens/nouveau': typeof AdminBiensNouveauRoute
  '/admin/biens/': typeof AdminBiensIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agence': typeof AgenceRoute
  '/alertes': typeof AlertesRoute
  '/calcul': typeof CalculRoute
  '/contact': typeof ContactRoute
  '/vendre': typeof VendreRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/equipe': typeof AdminEquipeRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/biens/$slug': typeof BiensSlugRoute
  '/admin': typeof AdminIndexRoute
  '/biens': typeof BiensIndexRoute
  '/admin/biens/$id': typeof AdminBiensIdRoute
  '/admin/biens/nouveau': typeof AdminBiensNouveauRoute
  '/admin/biens': typeof AdminBiensIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agence': typeof AgenceRoute
  '/alertes': typeof AlertesRoute
  '/calcul': typeof CalculRoute
  '/contact': typeof ContactRoute
  '/vendre': typeof VendreRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/equipe': typeof AdminEquipeRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/biens/$slug': typeof BiensSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/biens/': typeof BiensIndexRoute
  '/admin/biens/$id': typeof AdminBiensIdRoute
  '/admin/biens/nouveau': typeof AdminBiensNouveauRoute
  '/admin/biens/': typeof AdminBiensIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agence'
    | '/alertes'
    | '/calcul'
    | '/contact'
    | '/vendre'
    | '/admin/contacts'
    | '/admin/equipe'
    | '/admin/login'
    | '/admin/parametres'
    | '/biens/$slug'
    | '/admin/'
    | '/biens/'
    | '/admin/biens/$id'
    | '/admin/biens/nouveau'
    | '/admin/biens/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agence'
    | '/alertes'
    | '/calcul'
    | '/contact'
    | '/vendre'
    | '/admin/contacts'
    | '/admin/equipe'
    | '/admin/login'
    | '/admin/parametres'
    | '/biens/$slug'
    | '/admin'
    | '/biens'
    | '/admin/biens/$id'
    | '/admin/biens/nouveau'
    | '/admin/biens'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agence'
    | '/alertes'
    | '/calcul'
    | '/contact'
    | '/vendre'
    | '/admin/contacts'
    | '/admin/equipe'
    | '/admin/login'
    | '/admin/parametres'
    | '/biens/$slug'
    | '/admin/'
    | '/biens/'
    | '/admin/biens/$id'
    | '/admin/biens/nouveau'
    | '/admin/biens/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgenceRoute: typeof AgenceRoute
  AlertesRoute: typeof AlertesRoute
  CalculRoute: typeof CalculRoute
  ContactRoute: typeof ContactRoute
  VendreRoute: typeof VendreRoute
  BiensSlugRoute: typeof BiensSlugRoute
  BiensIndexRoute: typeof BiensIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendre': {
      id: '/vendre'
      path: '/vendre'
      fullPath: '/vendre'
      preLoaderRoute: typeof VendreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calcul': {
      id: '/calcul'
      path: '/calcul'
      fullPath: '/calcul'
      preLoaderRoute: typeof CalculRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertes': {
      id: '/alertes'
      path: '/alertes'
      fullPath: '/alertes'
      preLoaderRoute: typeof AlertesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agence': {
      id: '/agence'
      path: '/agence'
      fullPath: '/agence'
      preLoaderRoute: typeof AgenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biens/': {
      id: '/biens/'
      path: '/biens'
      fullPath: '/biens/'
      preLoaderRoute: typeof BiensIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/biens/$slug': {
      id: '/biens/$slug'
      path: '/biens/$slug'
      fullPath: '/biens/$slug'
      preLoaderRoute: typeof BiensSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/parametres': {
      id: '/admin/parametres'
      path: '/parametres'
      fullPath: '/admin/parametres'
      preLoaderRoute: typeof AdminParametresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/equipe': {
      id: '/admin/equipe'
      path: '/equipe'
      fullPath: '/admin/equipe'
      preLoaderRoute: typeof AdminEquipeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contacts': {
      id: '/admin/contacts'
      path: '/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof AdminContactsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/biens/': {
      id: '/admin/biens/'
      path: '/biens'
      fullPath: '/admin/biens/'
      preLoaderRoute: typeof AdminBiensIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/biens/nouveau': {
      id: '/admin/biens/nouveau'
      path: '/biens/nouveau'
      fullPath: '/admin/biens/nouveau'
      preLoaderRoute: typeof AdminBiensNouveauRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/biens/$id': {
      id: '/admin/biens/$id'
      path: '/biens/$id'
      fullPath: '/admin/biens/$id'
      preLoaderRoute: typeof AdminBiensIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminContactsRoute: typeof AdminContactsRoute
  AdminEquipeRoute: typeof AdminEquipeRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminParametresRoute: typeof AdminParametresRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBiensIdRoute: typeof AdminBiensIdRoute
  AdminBiensNouveauRoute: typeof AdminBiensNouveauRoute
  AdminBiensIndexRoute: typeof AdminBiensIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminContactsRoute: AdminContactsRoute,
  AdminEquipeRoute: AdminEquipeRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminParametresRoute: AdminParametresRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBiensIdRoute: AdminBiensIdRoute,
  AdminBiensNouveauRoute: AdminBiensNouveauRoute,
  AdminBiensIndexRoute: AdminBiensIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AgenceRoute: AgenceRoute,
  AlertesRoute: AlertesRoute,
  CalculRoute: CalculRoute,
  ContactRoute: ContactRoute,
  VendreRoute: VendreRoute,
  BiensSlugRoute: BiensSlugRoute,
  BiensIndexRoute: BiensIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
